
spring:
  profiles:
    active: prod

  servlet:
    session:
      timeout: 1800 # 세션 타임아웃을 1800초(30분)로 설정

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    #initialization-mode: always
    url:  jdbc:postgresql://kwaksh2319.cfgesasomkks.us-east-1.rds.amazonaws.com:5432/kwakshdb #jdbc:h2:file:~/db/webDemo # jdbc:h2:~/db/webDemo
    driver-class-name: org.postgresql.Driver  #  org.h2.Driver
    username: kwaksh2319
    password: rhkr1070912!
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
    # connection-test-query: SELECT 1
     maximum-pool-size: 20
     connection-timeout: 60000
     max-lifetime: 1800000
     idle-timeout: 600000
  jpa:
    show-sql: false
    format_sql: true
    use_sql_comments: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    #hibernate:
      #dialect: org.hibernate.dialect.H2Dialect # Hibernate dialect 설정 추가
      #ddl-auto: update
  #  defer-datasource-initialization: true

    open-in-view: false
   # properties:
     # javax:
      #  persistence:
        # schema-generation:
         #  scripts:
             # action: create
              #create-target: src/main/resources/create.sql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: false
#components:
 # schemas:
  #  YourSchema:
   #   type: object
    #    properties:
     #     category:
      #      type: object
       #     example: null
   #  springframework: debug
    # hibernate: DEBUG
     # root: debug
      #org.springframework: debug

  #logging.file:
    #  path: C:\logs
     # name: myapp.log
#---
#spring:
 # datasource:
  #  url: jdbc:h2:mem:test
  #config:
  #  activate:
   #   on-profile: test


